[[plugins]]
repo = 'Shougo/dein.vim'


[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = 'call shimies#init#vimproc#hook_post_update()'


[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source = 'call shimies#init#vim_indent_guides#hook_source()'


# vim: ft=yaml et ts=4 sts=4 sw=4
